name: "Generate Mock Data"
description: "Generate mock(synthetic) data for salesforce using smock-it."
author: "Divy Muni"

inputs:
  templates:
    description: "Provide comma-separated list of Template(s) name (e.g. lead_creation.json, account_update.json)"
    required: true
  org-alias:
    description: "Provide alias of connected salesforce org"
    required: true

runs:
  using: "composite"
  steps:
    - name: generate synthetic test data
      run: |
        DATA_GEN_PATH="data_gen"
        
        if [[ -z "$DATA_GEN_PATH" ]]; then
          DATA_GEN_PATH="data_gen"
          echo "SUCCESSFUL: Path is validated - $DATA_GEN_PATH"
        fi
        if [[ ! -d "$DATA_GEN_PATH" || ! -d "$DATA_GEN_PATH/templates" ]]; then
          echo "Error: Required directories ($DATA_GEN_PATH, templates) not found."
          exit 1
        fi
        
        echo "Installing Smock-it - mock data generator"
        echo "y" | sf plugins install smock-it@latest
        echo "Smock-it is installed successfully."

        IFS=',' read -ra TEMPLATE_LIST <<< "${{ inputs.templates }}"
        for TEMPLATE in "${TEMPLATE_LIST[@]}"; do
          echo "validating templates & generating synthetic data for : $TEMPLATE"
          sf data generate -a ${{ inputs.org-alias }} -t $TEMPLATE
        done
      shell: bash