name: "Smock-it - Test Data Generator"
description: "Generate mock/ dummy/ synthetic data for salesforce using smock-it"
author: "Divy Muni"

inputs:
  templates:
    description: "Comma separated list of Template(s) name (e.g. lead_creation.json, account_update.json)"
    required: true
  mockaroo-api-key:
    description: "Provide Mockaroo API key for data generation"
    required: true
  org-alias:
    description: "Salesforce Org Alias"
    required: true

runs:
  using: "composite"
  steps:
    - name: resolve data_gen directory
      id: check-dir
      run: |
        DATA_GEN_PATH="data_gen"
        if [[ -z "$DATA_GEN_PATH" ]]; then
          DATA_GEN_PATH="data_gen"
          echo "Path is validated Successfully"
        fi
        if [[ ! -d "$DATA_GEN_PATH" || ! -d "$DATA_GEN_PATH/templates" || ! -d "$DATA_GEN_PATH/output" ]]; then
          echo "Error: Required directories ($DATA_GEN_PATH, templates, output) not found."
          exit 1
        fi
        echo "Using data_gen path: $DATA_GEN_PATH"
        echo "DATA_GEN_PATH=$DATA_GEN_PATH" >> $GITHUB_ENV
      shell: bash
    - name: install smock-it
      run: |
        export MOCKAROO_API_KEY="${{ inputs.mockaroo-api-key }}"
        echo "y" | sf plugins install smock-it@latest
        echo "smock-it SF plugin installed."
      env:
        MOCKAROO_API_KEY: ${{ inputs.mockaroo-api-key }}
      shell: bash
    - name: generate synthetic data
      run: |
        export MOCKAROO_API_KEY="${{ inputs.mockaroo-api-key }}"
        IFS=',' read -ra TEMPLATE_LIST <<< "${{ inputs.templates }}"
        for TEMPLATE in "${TEMPLATE_LIST[@]}"; do
          echo "Validating & Generating synthetic data for : $TEMPLATE"
          sf data generate -a ${{ inputs.org-alias }} -t $TEMPLATE
        done
      shell: bash
      env:
        MOCKAROO_API_KEY: ${{ inputs.mockaroo-api-key }}
    - name: list output files
      run: ls -a $DATA_GEN_PATH/output
      shell: bash
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with: 
        path: $DATA_GEN_PATH/output/
        retention: 15
        if-no-files-found: ignore
