#For More Info, Visit https://github.com/concretios/smock-it/wiki/Smock%E2%80%90It-GitHub-Action
name: Smock-it Data Generation (Skeleton)

on:
  workflow_dispatch:
    inputs:
      templates:
        description: "Provide comma-separated template name(s) present in data_gen/templates"
        required: true
        type: string
      org-alias:
        description: "set common alias for org"
        required: true
        type: string
        default: "smockit"

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: install SF CLI
      run: |
        npm install -g @salesforce/cli
        echo "SF CLI Installed."
    - name: create server-key file from stored secrets
      run: |
        echo "${{ secrets.JWT_TOKEN }}" > server.key 
    - name: connect your org using jwt
      run: |
        sf org login jwt --client-id ${{ secrets.CLIENT_ID }} --jwt-key-file server.key --username ${{ secrets.USERNAME }} -r ${{secrets.INSTANCE_URL}} --alias ${{ inputs.org-alias }}
    - name: generate data using smock-it
      uses: concretios/smock-it@main
      with:
        templates: ${{ inputs.templates }}
        org-alias: ${{ inputs.org-alias }}
    - name: upload smock-it output
      uses: actions/upload-artifact@v4
      with: 
        name: SmockItOutputFiles
        path: data_gen/output/
        retention-days: 15
        if-no-files-found: warn 